# Generated by Django 6.0.3 on 2026-03-20 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='region',
            field=models.CharField(choices=[('Marmara', 'Marmara'), ('Ege', 'Ege'), ('İç Anadolu', 'İç Anadolu'), ('Akdeniz', 'Akdeniz'), ('Karadeniz', 'Karadeniz'), ('Doğu Anadolu', 'Doğu Anadolu'), ('Güneydoğu Anadolu', 'Güneydoğu Anadolu'), ('Genel', 'Genel (Tüm Türkiye)')], default='Genel', max_length=50),
        ),
    ]
