# Generated by Django 6.0.3 on 2026-03-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_author_question_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='country',
            field=models.CharField(choices=[('Türkiye', 'Türkiye'), ('ABD', 'Amerika Birleşik Devletleri'), ('Almanya', 'Almanya'), ('İngiltere', 'İngiltere'), ('Fransa', 'Fransa')], default='Türkiye', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Genel', 'Genel (Tüm Ülke)'), ('Bölgesel', 'Bölgesel')], default='Genel', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='region',
            field=models.CharField(blank=True, choices=[('Marmara', 'Marmara'), ('Ege', 'Ege'), ('İç Anadolu', 'İç Anadolu'), ('Akdeniz', 'Akdeniz'), ('Karadeniz', 'Karadeniz'), ('Doğu Anadolu', 'Doğu Anadolu'), ('Güneydoğu Anadolu', 'Güneydoğu Anadolu'), ('Genel', 'Genel (Tüm Türkiye)')], default='Genel', max_length=50, null=True),
        ),
    ]
