# Generated by Django 6.0.3 on 2026-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_is_private_results_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_preference',
            field=models.CharField(choices=[('Türkiye', 'Türkiye'), ('ABD', 'Amerika Birleşik Devletleri'), ('Almanya', 'Almanya'), ('İngiltere', 'İngiltere'), ('Fransa', 'Fransa')], default='Türkiye', max_length=50),
        ),
    ]
